# Site settings
title: DevOpsify
email: info@devopsify.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "devopsify.io" # the base hostname & protocol for your site

twitter_username: "devopsifyio"
github_username: "devopsify"

# Build settings
markdown: kramdown
